In [1]:
from sklearn.decomposition import PCA
import numpy as np

In [2]:
X = np.random.randint(1, 10, (5,5))

In [3]:
X

array([[4, 6, 9, 7, 7],
       [4, 5, 8, 6, 4],
       [1, 3, 9, 2, 5],
       [3, 5, 6, 5, 3],
       [2, 8, 3, 2, 9]])

In [4]:
pca = PCA(n_components = 2)

In [5]:
pca.fit(X)

PCA(copy=True, iterated_power='auto', n_components=2, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [6]:
Y = pca.fit_transform(X) # project X onto a lower dimensional matrix

In [7]:
Y

array([[-1.4983662 , -2.88247385],
       [-2.44294318, -1.04091014],
       [-1.26254338,  3.94311487],
       [-1.1721457 ,  0.23286892],
       [ 6.37599845, -0.25259979]])

In [8]:
X_reconstr = pca.inverse_transform(Y) # reconstruct X from Y

In [9]:
X_reconstr

array([[4.35465761, 6.14329117, 7.71987647, 7.0571317 , 5.52421257],
       [3.64731802, 4.92891723, 8.44495632, 6.1219769 , 4.57116801],
       [1.1712156 , 3.09530584, 8.07901166, 2.09300338, 3.95953749],
       [2.86880761, 4.83711893, 7.74759827, 4.70376914, 4.92516296],
       [1.95800116, 7.99536683, 3.00855728, 2.02411888, 9.01991898]])